### ISSUE TITLE
Get a private review link ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/zenodo#1]
Is it possible with Zenodo to have a private review link.

The idea is that a scientists submit a paper with supplementary material.
Would be nice that the referee can check those data in a 'private' way and that once the publication is accepted it really received a DOI.

Would this be possible ?

**Comment by targos** [comment]
I think it's feasible. We can "close" the entry on Zenodo until the paper is published

**Comment by targos** [comment]
This library can already be used to implement this
