### ISSUE TITLE
How to add a revised version ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/zenodo#2]
We should be able to resubmitted the information about a sample and there will be a revised version. I guess it will receive a new DOI but it should link the previous one ? Maybe a better way ?

**Comment by targos** [comment]
I'm not sure you can resubmit after publication

**Comment by lpatiny** [comment]
It seems there is a way to say that this is a revised version. Even if the original version will still be available.

You may have a look for example to : https://www.zenodo.org/record/1196821#.WrSZqpPwZTY

On the right we have:

![image](https://user-images.githubusercontent.com/1484241/37814169-f8475f8a-2e68-11e8-8bda-0830059ff5af.png)

I think we should plan this as well. I have already planned to be able to reload the information about a previously submitted dataset so hopefully it is easy to do and somehow just a meta information towards the previous version.

**Comment by targos** [comment]
From the documentation: http://developers.zenodo.org/#edit

New version
Create a new version of a deposition.

This action will create a new deposit, which will be a snapshot of the current resouce, inheriting the metadata as well as snapshot of files. The new version deposit will have a state similar to a new, unpublished deposit, most importantly its files will be modifiable as for a new deposit.

Only one unpublished new version deposit can be available at any moment, i.e.: calling new version action multiple times will have no effect, as long as the resulting new version deposit from the first call is not published or deleted.

NOTE: The response body of this action is NOT the new version deposit, but the original resource. The new version deposition can be accessed through the "latest_draft" under "links" in the response body.

HTTP Request
POST /api/deposit/depositions/:id/actions/newversion
