### ISSUE TITLE
allow to place 'meta' information in the _toc.json

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/zenodo#7]
When submitting a list of product to Zenodo we need to be able to add some meta information about the entry that is only useful in the context of Zenodo.

The only case I'm currently thinking at is the number of the molecule in the paper. In the supplementary material we need to give the same labelling like1a, 5c, ... as the one described in the paper.

What I suggest is that when we save the kind 'zenodo' we are allowed at the level of an entry to add a property `meta` and this `meta` information will be copie in _toc.json.

![image](https://user-images.githubusercontent.com/1484241/39060321-529961c2-44c1-11e8-9a46-5d5ef5e62503.png)

**Comment by lpatiny** [comment]
@targos

**Comment by lpatiny** [comment]
The way I'm thinking at the level of the user interface is that each time we add an entry the view ask for the meta informations in a dialog box.

**Comment by targos** [comment]
can you open this in the correct repo? this is just the API to communicate with Zenodo

**Comment by targos** [comment]
https://github.com/cheminfo/rest-on-couch/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
